apiVersion: v1
kind: Secret
metadata:
  name: strapi-secrets
type: Opaque
data:
  ADMIN_JWT_SECRET: {{ .Values.adminJWTSecret | b64enc | quote }}
  DATABASE_URL : {{ .Values.databaseUrl | b64enc | quote }}