apiVersion: v1
kind: Secret
metadata:
  name: {{ include "strapi.fullname" . }}
type: Opaque
data:
  ADMIN_JWT_SECRET: {{ .Values.adminJWTSecret | b64enc | quote }}
  {{ if .Values.secrets.databaseUrl }}
  DATABASE_URL: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  {{ end }}
  