apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  labels:
    {{- include "saleor-helm.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "saleor-helm.selectorLabelsCelery" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "saleor-helm.selectorLabelsCelery" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "saleor-helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            runAsUser: 999
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range .Values.global.env }}
            - name: {{ .name }}
              value: {{ .value | quote}}
          {{- end }}
            - name: ALLOWED_HOSTS
              value: {{ .Values.global.allowedHosts }}
            - name: ALLOWED_CLIENT_HOSTS
              value: {{ .Values.global.allowedHosts }}
          envFrom:
          - secretRef:
              name: saleor-secrets
          args:
            - celery 
            - --app=saleor 
            - --app=saleor.celeryconf:app 
            - worker
            - --loglevel=INFO
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - timeout 10 celery -b $CELERY_BROKER_URL inspect ping -d celery@$HOSTNAME
            failureThreshold: 1
            initialDelaySeconds: 30
            periodSeconds: 40
            successThreshold: 1
            timeoutSeconds: 10  
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - timeout 10 celery -b $CELERY_BROKER_URL inspect ping -d celery@$HOSTNAME
            failureThreshold: 1
            initialDelaySeconds: 30
            periodSeconds: 40
            successThreshold: 1
            timeoutSeconds: 10  
          resources:
            {{- toYaml .Values.celeryrunner.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
