{{- $fullName := include "gtm-server-container-cluster.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gtm-server-container-cluster.fullname" . }}
  labels:
    {{- include "gtm-server-container-cluster.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gtm-server-container-cluster.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/type: "tagging"
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ $fullName }}-preview"
  labels:
    {{- include "gtm-server-container-cluster.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/type: "preview"
    
